### ISSUE TITLE
Class extends value undefined

### ISSUE THREAD

**Issue by pal-pinter** [cult-of-coders/apollo#44]
Hi,

after install:

meteor add cultofcoders:apollo

```
W20180803-10:41:27.398(2)? (STDERR) TypeError: Class extends value undefined is not a constructor or null
W20180803-10:41:27.399(2)? (STDERR)     at MongoDirective.js (packages/cultofcoders:grapher-schema-directives/MongoDirective.js:4:45)
W20180803-10:41:27.399(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180803-10:41:27.399(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180803-10:41:27.399(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180803-10:41:27.399(2)? (STDERR)     at LinkDirective.js (packages/cultofcoders:grapher-schema-directives/LinkDirective.js:1:472)
W20180803-10:41:27.399(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180803-10:41:27.400(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180803-10:41:27.400(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180803-10:41:27.400(2)? (STDERR)     at index.js (packages/cultofcoders:grapher-schema-directives/index.js:1:333)
W20180803-10:41:27.400(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180803-10:41:27.400(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180803-10:41:27.400(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180803-10:41:27.401(2)? (STDERR)     at /home/palpinter/Fejlesztés/militia/apollo-server/.meteor/local/build/programs/server/packages/cultofcoders_grapher-schema-directives.js:364:15
W20180803-10:41:27.401(2)? (STDERR)     at /home/palpinter/Fejlesztés/militia/apollo-server/.meteor/local/build/programs/server/packages/cultofcoders_grapher-schema-directives.js:369:3
W20180803-10:41:27.401(2)? (STDERR)     at /home/palpinter/Fejlesztés/militia/apollo-server/.meteor/local/build/programs/server/boot.js:411:36
W20180803-10:41:27.401(2)? (STDERR)     at Array.forEach (<anonymous>)

```
Thx Pal

**Comment by pal-pinter** [comment]
After reinstalling everything some times error gone.
