### ISSUE TITLE
Shouldn't require resolvers for links.

### ISSUE THREAD

**Issue by 1337cookie** [cult-of-coders/apollo#65]
Am I correct in thinking that using the grapher schema directives in this package I should not have to write resolvers for the linked graphql types?

**If i run this query:**
```
query{
vehicleManufacturers{
  _id
  name
  VehicleModels{
    _id
    name
  }
}
}
```
**Results:**
```
{
  "data": {
    "vehicleManufacturers": [
      {
        "_id": "j3Es5PAkoABKofAtG",
        "name": "Toyota",
        "VehicleModels": null
      }
    ]
  }
}
```
**And this query:**
```
query{
 vehicleModels{
  _id
  name
  VehicleManufacturer{
    _id
    name
  }
}
}
```
**Results:**
```
{
  "errors": [
    {
      "message": "parentResult[fieldStorage].forEach is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "vehicleModels"
      ]
    }
  ],
  "data": {
    "vehicleModels": null
  }
}
```

This is what my files look like. 

Schema.graphql:

```
type VehicleManufacturer @mongo(name:"VehicleManufacturers"){
	_id: String
	#Toyota, Nissan etc.
	name: String
	VehicleModels: [VehicleModel] @link(to:"VehicleManufacturer")
}
type VehicleModel @mongo(name:"VehicleModels"){
	_id: String
	#Hilux, Terrano etc.
	name: String
	VehicleManufacturer: [VehicleManufacturer] @link(field:"vehicleManufacturerId")
}
```
resolvers.js:

```
Query: {
	vehicleManufacturers(_, args, { db }, ast) {
		return db.VehicleManufacturers.astToQuery(ast).fetch();
	},
	vehicleModels(_, args, { db }, ast) {
		return db.VehicleModels.astToQuery(ast).fetch();
	}
},
```

**Comment by 1337cookie** [comment]
Here is the terminal output of the error for posterity;

```
parentResult[fieldStorage].forEach is not a function

 GraphQL request (2:3)
 1: {
 2:   vehicleModels {
      ^
 3:     _id

  {
     "message": "parentResult[fieldStorage].forEach is not a function",
     "locations": [
         {
             "line": 2,
             "column": 3
         }
     ],
     "path": [
         "vehicleModels"
     ],
     "extensions": {
         "code": "INTERNAL_SERVER_ERROR",
         "exception": {
             "stacktrace": [
                 "TypeError: parentResult[fieldStorage].forEach is not a function",
                 "    at parent.results.forEach.parentResult (packages/cultofcoders:grapher/lib/query/hypernova/assembler.js:53:40)",
                 "    at Array.forEach (<anonymous>)",
                 "    at module.exportDefault (packages/cultofcoders:grapher/lib/query/hypernova/assembler.js:47:24)",
                 "    at storeHypernovaResults (packages/cultofcoders:grapher/lib/query/hypernova/storeHypernovaResults.js:36:9)",
                 "    at _.each.childCollectionNode (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:9:9)",
                 "    at Array.forEach (<anonymous>)",
                 "    at Function._.each._.forEach (packages\\underscore.js:139:11)",
                 "    at hypernova (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:6:7)",
                 "    at hypernovaInit (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:25:5)",
                 "    at Query.fetch (packages/cultofcoders:grapher/lib/query/query.server.js:18:16)",
                 "    at vehicleModels (server/resolvers.js:33:44)",
                 "    at field.resolve (C:\\Users\\root\\Documents\\culttest\\node_modules\\graphql-extensions\\dist\\index.js:128:26)",
                 "    at resolveFieldValueOrError (C:\\Users\\root\\Documents\\culttest\\node_modules\\graphql\\execution\\execute.js:479:18)",
                 "    at resolveField (C:\\Users\\root\\Documents\\culttest\\node_modules\\graphql\\execution\\execute.js:446:16)",
                 "    at executeFields (C:\\Users\\root\\Documents\\culttest\\node_modules\\graphql\\execution\\execute.js:293:18)",
                 "    at executeOperation (C:\\Users\\root\\Documents\\culttest\\node_modules\\graphql\\execution\\execute.js:237:122)"
             ]
         }
     }
 }
```

**Comment by theodorDiaconu** [comment]
This was fixed inside Grapher I remember. If not submit it there and show me how to reproduce it in a repo.
